version: '3.8'

services:
  dipsip-client:
    build: .
    container_name: dipsip-client
    ports:
      - "4000:4000"
    environment:
      # These variables are loaded from the .env file
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - DATA_ROOT_FOLDER=${DATA_ROOT_FOLDER}
    volumes:
      # This volume mounts your local data directory to the container.
      # The `KITE_ACCESS_TOKEN_DATA_FOLDER` in your .env must match the path on your machine.
      # This is crucial for the `check_token_validity.js` script to find the file.
      - ./.env:/.env
      - ${KITE_ACCESS_TOKEN_DATA_FOLDER:-~}:/app/data
    restart: unless-stopped
    networks:
      - dipsip_inter_service_network
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: http dipsip-client:4000
    depends_on:
      - dipsip-client
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}  # Put this in your .env file  
    ports:
      - "4040:4040"
    networks:
      - dipsip_inter_service_network  
networks: # ADDED: Declare the external network
  dipsip_inter_service_network:
    external: true      