version: '3.8'

services:
  dipsip-client:
    build: .
    container_name: dipsip-client
    ports:
      - "4000:4000"
    environment:
      # These variables are loaded from the .env file
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - DATA_ROOT_FOLDER=${DATA_ROOT_FOLDER}
    volumes:
      # This volume mounts your local data directory to the container.
      # The `DATA_ROOT_FOLDER` in your .env must match the path on your machine.
      # This is crucial for the `check_token_validity.js` script to find the file.
      - ./.env:/.env
      - ${DATA_ROOT_FOLDER:-/home/user/data}:/app/data
    restart: unless-stopped